add Tencent-vectorDB and tencent-cos
BorisPolonsky/dify-helm pull request #104
Opened 2024-12-24 11:03 UTC by PeihuaLiang

2024-12-24 13:58 UTC, BorisPolonsky commented
Thanks for you contribution. 
To opt in new object storages, adjustments should be made here too
https://github.com/BorisPolonsky/dify-helm/blob/0d534465fa28418dea6ef01ec7d21a3427feeacf/charts/dify/templates/api-deployment.yaml#L2

2024-12-24 14:26 UTC, BorisPolonsky requested changes

2024-12-24 14:26 UTC, BorisPolonsky commented on charts/dify/values.yaml
> +externalTencent:
We'll need a canonical name for this vector database instead of  `Tencent` which suggests the name of the enterprise itself

2024-12-24 14:26 UTC, BorisPolonsky commented on charts/dify/templates/config.tpl
> +{{- else if .Values.externalTencent.enabled}}
We'll need a canonical name for this vector database instead of  `Tencent` which suggests the name of the enterprise itself

2024-12-31 03:24 UTC, liangpeihuahua reviewed
Please check if there is any problem with the code, and let us work together to upgrade subsequent versions to the version that is synchronized with the official diify

2024-12-31 04:58 UTC, BorisPolonsky commented
> Please check if there is any problem with the code, and let us work together to upgrade subsequent versions to the version that is synchronized with the official diify

I'm currently on vacation

2025-01-03 13:54 UTC, BorisPolonsky approved these changes

2025-01-03 13:55 UTC, merged