add external pgvector
BorisPolonsky/dify-helm pull request #79
Opened 2024-06-25 03:23 UTC by FingerLiu

2024-06-25 04:15 UTC, BorisPolonsky commented
Thanks for your contribution. Could you please change target branch to 'dev' instead since we have other on going updates to be merged as well.

2024-06-26 02:04 UTC, FingerLiu commented
changed to dev

2024-06-26 04:02 UTC, BorisPolonsky requested changes

2024-06-26 04:02 UTC, BorisPolonsky commented on charts/dify/templates/config.tpl
> -MILVUS_SECURE: {{ .Values.externalMilvus.useTLS | toString | quote }}
Please restore this config

2024-06-26 04:02 UTC, BorisPolonsky commented on charts/dify/templates/config.tpl
> +# Milvus configuration Only available when VECTOR_STORE is `pgvector`.
Please update this comment

2024-06-26 06:11 UTC, FingerLiu commented
done

2024-06-27 10:42 UTC, BorisPolonsky submitted a review, later dismissed

2024-06-27 11:54 UTC, BorisPolonsky requested changes
Please restore Milvus TLS config.

https://github.com/BorisPolonsky/dify-helm/pull/79/commits/04967506a741565fc1c95f66652e5e8cba972bc9#diff-b66d04a8a753c83075f115c52ba2ba47bebe8e3205335f8ddca381903fb74397L235

2024-07-02 02:07 UTC, FingerLiu commented
restored Milvus TLS config

2024-07-02 06:35 UTC, merged