Add a flexible set of clientMaxBodySize limits
BorisPolonsky/dify-helm pull request #97
Opened 2024-12-10 12:03 UTC by raknamber1

2024-12-11 06:08 UTC, BorisPolonsky requested changes
Minor adjustment needed in comment

2024-12-11 06:08 UTC, BorisPolonsky commented on charts/dify/values.yaml
> +  ## @param.clientMaxBodySize Custom client_max_body_size param nginx default: 15m
keyword `proxy` was missing. Do you mean
`## @param proxy.clientMaxBodySize Custom client_max_body_size param nginx default: 15m`

2024-12-11 09:29 UTC, raknamber1 commented
@BorisPolonsky I fixed it, you can look at it again

2024-12-11 11:24 UTC, BorisPolonsky approved these changes

2024-12-11 11:25 UTC, merged

2024-12-11 11:35 UTC, raknamber1 commented
@BorisPolonsky please tell me, can we release this or do we need to wait for other changes?

2024-12-12 02:18 UTC, BorisPolonsky commented
> @BorisPolonsky please tell me, can we release this or do we need to wait for other changes?

I'm currently busy with my work. If you need this feature ASAP you can pull from master branch and make a package of your own with `helm package` command. It's advised to maintain a temporary version tag in `Chart.yaml` for this purpose